// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 4 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int matrixconnectionsbuffer_4 = 4;
	/// <summary>PID: 4 | Type: read</summary>
	public const int matrixconnectionsbuffer = 4;
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int matrixviewpagecontrol_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int matrixviewpagecontrol = 5;
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int tableviewpagecontrol_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int tableviewpagecontrol = 6;
	/// <summary>PID: 99 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int matrixcolumntype_99 = 99;
	/// <summary>PID: 99 | Type: read</summary>
	public const int matrixcolumntype = 99;
	/// <summary>PID: 105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int matrixserialized_105 = 105;
	/// <summary>PID: 105 | Type: read</summary>
	public const int matrixserialized = 105;
	/// <summary>PID: 124 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int matrixsettings_displaytype_124 = 124;
	/// <summary>PID: 124 | Type: read</summary>
	public const int matrixsettings_displaytype = 124;
	/// <summary>PID: 1400 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int routersyslevelwritebuffer_1400 = 1400;
	/// <summary>PID: 1400 | Type: read</summary>
	public const int routersyslevelwritebuffer = 1400;
	/// <summary>PID: 1401 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int routersyslevelwriteoid_1401 = 1401;
	/// <summary>PID: 1401 | Type: read</summary>
	public const int routersyslevelwriteoid = 1401;
	/// <summary>PID: 1403 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int routersyslevelreadvalue_1403 = 1403;
	/// <summary>PID: 1403 | Type: read</summary>
	public const int routersyslevelreadvalue = 1403;
	/// <summary>PID: 1404 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int routersysleveltakenextwritebufferitem_1404 = 1404;
	/// <summary>PID: 1404 | Type: read</summary>
	public const int routersysleveltakenextwritebufferitem = 1404;
	public class Write
	{
		/// <summary>PID: 101 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int matrix_101 = 101;
		/// <summary>PID: 101 | Type: write</summary>
		public const int matrix = 101;
		/// <summary>PID: 125 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int matrixsettings_displaytype_125 = 125;
		/// <summary>PID: 125 | Type: write</summary>
		public const int matrixsettings_displaytype = 125;
		/// <summary>PID: 1052 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontrolinputslabel_1052 = 1052;
		/// <summary>PID: 1052 | Type: write</summary>
		public const int routercontrolinputslabel = 1052;
		/// <summary>PID: 1053 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontrolinputsisenabled_1053 = 1053;
		/// <summary>PID: 1053 | Type: write</summary>
		public const int routercontrolinputsisenabled = 1053;
		/// <summary>PID: 1054 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontrolinputsislocked_1054 = 1054;
		/// <summary>PID: 1054 | Type: write</summary>
		public const int routercontrolinputsislocked = 1054;
		/// <summary>PID: 1055 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontrolinputsnotes_1055 = 1055;
		/// <summary>PID: 1055 | Type: write</summary>
		public const int routercontrolinputsnotes = 1055;
		/// <summary>PID: 1152 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputslabel_1152 = 1152;
		/// <summary>PID: 1152 | Type: write</summary>
		public const int routercontroloutputslabel = 1152;
		/// <summary>PID: 1153 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsisenabled_1153 = 1153;
		/// <summary>PID: 1153 | Type: write</summary>
		public const int routercontroloutputsisenabled = 1153;
		/// <summary>PID: 1154 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsislocked_1154 = 1154;
		/// <summary>PID: 1154 | Type: write</summary>
		public const int routercontroloutputsislocked = 1154;
		/// <summary>PID: 1155 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsnotes_1155 = 1155;
		/// <summary>PID: 1155 | Type: write</summary>
		public const int routercontroloutputsnotes = 1155;
		/// <summary>PID: 1156 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsconnectedinput_1156 = 1156;
		/// <summary>PID: 1156 | Type: write</summary>
		public const int routercontroloutputsconnectedinput = 1156;
		/// <summary>PID: 1160 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsvirtualsets_1160 = 1160;
		/// <summary>PID: 1160 | Type: write</summary>
		public const int routercontroloutputsvirtualsets = 1160;
		/// <summary>PID: 1161 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routercontroloutputsserializedsets_1161 = 1161;
		/// <summary>PID: 1161 | Type: write</summary>
		public const int routercontroloutputsserializedsets = 1161;
		/// <summary>PID: 1402 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routersyslevelwritevalue_1402 = 1402;
		/// <summary>PID: 1402 | Type: write</summary>
		public const int routersyslevelwritevalue = 1402;
		/// <summary>PID: 1405 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int routersyslevelwritevalueinteger_1405 = 1405;
		/// <summary>PID: 1405 | Type: write</summary>
		public const int routersyslevelwritevalueinteger = 1405;
	}
	public class Matrix
	{
		/// <summary>PID: 100</summary>
		public const int tablePid = 100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		public class Pid
		{
			public class Write
			{
			}
		}
		public class Idx
		{
		}
	}
	public class Routercontrolinputs
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsnumber_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int routercontrolinputsnumber = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputslabel_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int routercontrolinputslabel = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsisenabled_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int routercontrolinputsisenabled = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsislocked_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int routercontrolinputsislocked = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsnotes_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int routercontrolinputsnotes = 1005;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsnumber_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int routercontrolinputsnumber = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputslabel_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int routercontrolinputslabel = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsisenabled_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int routercontrolinputsisenabled = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsislocked_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int routercontrolinputsislocked = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontrolinputsnotes_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int routercontrolinputsnotes = 4;
		}
	}
	public class Routercontroloutputs
	{
		/// <summary>PID: 1100</summary>
		public const int tablePid = 1100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1101</summary>
		public const int indexColumnPid = 1101;
		public class Pid
		{
			/// <summary>PID: 1101 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsnumber_1101 = 1101;
			/// <summary>PID: 1101 | Type: read</summary>
			public const int routercontroloutputsnumber = 1101;
			/// <summary>PID: 1102 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputslabel_1102 = 1102;
			/// <summary>PID: 1102 | Type: read</summary>
			public const int routercontroloutputslabel = 1102;
			/// <summary>PID: 1103 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsisenabled_1103 = 1103;
			/// <summary>PID: 1103 | Type: read</summary>
			public const int routercontroloutputsisenabled = 1103;
			/// <summary>PID: 1104 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsislocked_1104 = 1104;
			/// <summary>PID: 1104 | Type: read</summary>
			public const int routercontroloutputsislocked = 1104;
			/// <summary>PID: 1105 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsnotes_1105 = 1105;
			/// <summary>PID: 1105 | Type: read</summary>
			public const int routercontroloutputsnotes = 1105;
			/// <summary>PID: 1106 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsconnectedinput_1106 = 1106;
			/// <summary>PID: 1106 | Type: read</summary>
			public const int routercontroloutputsconnectedinput = 1106;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsnumber_1101 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int routercontroloutputsnumber = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputslabel_1102 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int routercontroloutputslabel = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsisenabled_1103 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int routercontroloutputsisenabled = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsislocked_1104 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int routercontroloutputsislocked = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsnotes_1105 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int routercontroloutputsnotes = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routercontroloutputsconnectedinput_1106 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int routercontroloutputsconnectedinput = 5;
		}
	}
	public class Routersysleveloutputs
	{
		/// <summary>PID: 1200</summary>
		public const int tablePid = 1200;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1201</summary>
		public const int indexColumnPid = 1201;
		public class Pid
		{
			/// <summary>PID: 1201 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsinstance_1201 = 1201;
			/// <summary>PID: 1201 | Type: read</summary>
			public const int routersysleveloutputsinstance = 1201;
			/// <summary>PID: 1202 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsname_1202 = 1202;
			/// <summary>PID: 1202 | Type: read</summary>
			public const int routersysleveloutputsname = 1202;
			/// <summary>PID: 1203 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputslocked_1203 = 1203;
			/// <summary>PID: 1203 | Type: read</summary>
			public const int routersysleveloutputslocked = 1203;
			/// <summary>PID: 1204 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsinputstatus_1204 = 1204;
			/// <summary>PID: 1204 | Type: read</summary>
			public const int routersysleveloutputsinputstatus = 1204;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsinstance_1201 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int routersysleveloutputsinstance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsname_1202 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int routersysleveloutputsname = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputslocked_1203 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int routersysleveloutputslocked = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersysleveloutputsinputstatus_1204 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int routersysleveloutputsinputstatus = 3;
		}
	}
	public class Routersyslevelinputs
	{
		/// <summary>PID: 1300</summary>
		public const int tablePid = 1300;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1301</summary>
		public const int indexColumnPid = 1301;
		public class Pid
		{
			/// <summary>PID: 1301 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputsinstance_1301 = 1301;
			/// <summary>PID: 1301 | Type: read</summary>
			public const int routersyslevelinputsinstance = 1301;
			/// <summary>PID: 1302 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputsname_1302 = 1302;
			/// <summary>PID: 1302 | Type: read</summary>
			public const int routersyslevelinputsname = 1302;
			/// <summary>PID: 1303 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputslocked_1303 = 1303;
			/// <summary>PID: 1303 | Type: read</summary>
			public const int routersyslevelinputslocked = 1303;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputsinstance_1301 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int routersyslevelinputsinstance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputsname_1302 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int routersyslevelinputsname = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int routersyslevelinputslocked_1303 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int routersyslevelinputslocked = 2;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 101  | Type: write</summary>
	public System.Object Matrix {get { return Protocol.GetParameter(101); }set { Protocol.SetParameter(101, value); }}
	/// <summary>PID: 125  | Type: write | DISCREETS: Matrix = 1, Tables = 2, Matrix and Tables = 3</summary>
	public System.Object Matrixsettings_displaytype {get { return Protocol.GetParameter(125); }set { Protocol.SetParameter(125, value); }}
	/// <summary>PID: 1052  | Type: write</summary>
	public System.Object Routercontrolinputslabel {get { return Protocol.GetParameter(1052); }set { Protocol.SetParameter(1052, value); }}
	/// <summary>PID: 1053  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Routercontrolinputsisenabled {get { return Protocol.GetParameter(1053); }set { Protocol.SetParameter(1053, value); }}
	/// <summary>PID: 1054  | Type: write | DISCREETS: Unlocked = 0, Locked = 1</summary>
	public System.Object Routercontrolinputsislocked {get { return Protocol.GetParameter(1054); }set { Protocol.SetParameter(1054, value); }}
	/// <summary>PID: 1055  | Type: write</summary>
	public System.Object Routercontrolinputsnotes {get { return Protocol.GetParameter(1055); }set { Protocol.SetParameter(1055, value); }}
	/// <summary>PID: 1152  | Type: write</summary>
	public System.Object Routercontroloutputslabel {get { return Protocol.GetParameter(1152); }set { Protocol.SetParameter(1152, value); }}
	/// <summary>PID: 1153  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Routercontroloutputsisenabled {get { return Protocol.GetParameter(1153); }set { Protocol.SetParameter(1153, value); }}
	/// <summary>PID: 1154  | Type: write | DISCREETS: Unlocked = 0, Locked = 1</summary>
	public System.Object Routercontroloutputsislocked {get { return Protocol.GetParameter(1154); }set { Protocol.SetParameter(1154, value); }}
	/// <summary>PID: 1155  | Type: write</summary>
	public System.Object Routercontroloutputsnotes {get { return Protocol.GetParameter(1155); }set { Protocol.SetParameter(1155, value); }}
	/// <summary>PID: 1156  | Type: write</summary>
	public System.Object Routercontroloutputsconnectedinput {get { return Protocol.GetParameter(1156); }set { Protocol.SetParameter(1156, value); }}
	/// <summary>PID: 1160  | Type: write</summary>
	public System.Object Routercontroloutputsvirtualsets {get { return Protocol.GetParameter(1160); }set { Protocol.SetParameter(1160, value); }}
	/// <summary>PID: 1161  | Type: write</summary>
	public System.Object Routercontroloutputsserializedsets {get { return Protocol.GetParameter(1161); }set { Protocol.SetParameter(1161, value); }}
	/// <summary>PID: 1402  | Type: write</summary>
	public System.Object Routersyslevelwritevalue {get { return Protocol.GetParameter(1402); }set { Protocol.SetParameter(1402, value); }}
	/// <summary>PID: 1405  | Type: write</summary>
	public System.Object Routersyslevelwritevalueinteger {get { return Protocol.GetParameter(1405); }set { Protocol.SetParameter(1405, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 100</summary>
	MatrixQActionTable matrix { get; set; }
	/// <summary>PID: 1000</summary>
	RoutercontrolinputsQActionTable routercontrolinputs { get; set; }
	/// <summary>PID: 1100</summary>
	RoutercontroloutputsQActionTable routercontroloutputs { get; set; }
	/// <summary>PID: 1200</summary>
	RoutersysleveloutputsQActionTable routersysleveloutputs { get; set; }
	/// <summary>PID: 1300</summary>
	RoutersyslevelinputsQActionTable routersyslevelinputs { get; set; }
	object Bus_bus { get; set; }
	object Matrixconnectionsbuffer_4 { get; set; }
	object Matrixconnectionsbuffer { get; set; }
	object Matrixviewpagecontrol_5 { get; set; }
	object Matrixviewpagecontrol { get; set; }
	object Tableviewpagecontrol_6 { get; set; }
	object Tableviewpagecontrol { get; set; }
	object Discreetinfo_discreetinfo { get; set; }
	object Matrixcolumntype_99 { get; set; }
	object Matrixcolumntype { get; set; }
	object Matrix_101 { get; set; }
	object Matrix { get; set; }
	object Matrixserialized_105 { get; set; }
	object Matrixserialized { get; set; }
	object Matrixsettings_displaytype_124 { get; set; }
	object Matrixsettings_displaytype { get; set; }
	object Matrixsettings_displaytype_125 { get; set; }
	object Routercontrolinputsnumber_1001 { get; set; }
	object Routercontrolinputsnumber { get; set; }
	object Routercontrolinputslabel_1002 { get; set; }
	object Routercontrolinputslabel { get; set; }
	object Routercontrolinputsisenabled_1003 { get; set; }
	object Routercontrolinputsisenabled { get; set; }
	object Routercontrolinputsislocked_1004 { get; set; }
	object Routercontrolinputsislocked { get; set; }
	object Routercontrolinputsnotes_1005 { get; set; }
	object Routercontrolinputsnotes { get; set; }
	object Routercontrolinputslabel_1052 { get; set; }
	object Routercontrolinputsisenabled_1053 { get; set; }
	object Routercontrolinputsislocked_1054 { get; set; }
	object Routercontrolinputsnotes_1055 { get; set; }
	object Routercontroloutputsnumber_1101 { get; set; }
	object Routercontroloutputsnumber { get; set; }
	object Routercontroloutputslabel_1102 { get; set; }
	object Routercontroloutputslabel { get; set; }
	object Routercontroloutputsisenabled_1103 { get; set; }
	object Routercontroloutputsisenabled { get; set; }
	object Routercontroloutputsislocked_1104 { get; set; }
	object Routercontroloutputsislocked { get; set; }
	object Routercontroloutputsnotes_1105 { get; set; }
	object Routercontroloutputsnotes { get; set; }
	object Routercontroloutputsconnectedinput_1106 { get; set; }
	object Routercontroloutputsconnectedinput { get; set; }
	object Routercontroloutputslabel_1152 { get; set; }
	object Routercontroloutputsisenabled_1153 { get; set; }
	object Routercontroloutputsislocked_1154 { get; set; }
	object Routercontroloutputsnotes_1155 { get; set; }
	object Routercontroloutputsconnectedinput_1156 { get; set; }
	object Routercontroloutputsvirtualsets_1160 { get; set; }
	object Routercontroloutputsvirtualsets { get; set; }
	object Routercontroloutputsserializedsets_1161 { get; set; }
	object Routercontroloutputsserializedsets { get; set; }
	object Routersysleveloutputsinstance_1201 { get; set; }
	object Routersysleveloutputsinstance { get; set; }
	object Routersysleveloutputsname_1202 { get; set; }
	object Routersysleveloutputsname { get; set; }
	object Routersysleveloutputslocked_1203 { get; set; }
	object Routersysleveloutputslocked { get; set; }
	object Routersysleveloutputsinputstatus_1204 { get; set; }
	object Routersysleveloutputsinputstatus { get; set; }
	object Routersyslevelinputsinstance_1301 { get; set; }
	object Routersyslevelinputsinstance { get; set; }
	object Routersyslevelinputsname_1302 { get; set; }
	object Routersyslevelinputsname { get; set; }
	object Routersyslevelinputslocked_1303 { get; set; }
	object Routersyslevelinputslocked { get; set; }
	object Routersyslevelwritebuffer_1400 { get; set; }
	object Routersyslevelwritebuffer { get; set; }
	object Routersyslevelwriteoid_1401 { get; set; }
	object Routersyslevelwriteoid { get; set; }
	object Routersyslevelwritevalue_1402 { get; set; }
	object Routersyslevelwritevalue { get; set; }
	object Routersyslevelreadvalue_1403 { get; set; }
	object Routersyslevelreadvalue { get; set; }
	object Routersysleveltakenextwritebufferitem_1404 { get; set; }
	object Routersysleveltakenextwritebufferitem { get; set; }
	object Routersyslevelwritevalueinteger_1405 { get; set; }
	object Routersyslevelwritevalueinteger { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 100</summary>
	public MatrixQActionTable matrix { get; set; }
	/// <summary>PID: 1000</summary>
	public RoutercontrolinputsQActionTable routercontrolinputs { get; set; }
	/// <summary>PID: 1100</summary>
	public RoutercontroloutputsQActionTable routercontroloutputs { get; set; }
	/// <summary>PID: 1200</summary>
	public RoutersysleveloutputsQActionTable routersysleveloutputs { get; set; }
	/// <summary>PID: 1300</summary>
	public RoutersyslevelinputsQActionTable routersyslevelinputs { get; set; }
	/// <summary>PID: 1  | Type: bus</summary>
	public System.Object Bus_bus {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 4  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixconnectionsbuffer_4 {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 4  | Type: read</summary>
	public System.Object Matrixconnectionsbuffer {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Show = 1, Hide = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixviewpagecontrol_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Show = 1, Hide = 2</summary>
	public System.Object Matrixviewpagecontrol {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Show = 1, Hide = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Tableviewpagecontrol_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Show = 1, Hide = 2</summary>
	public System.Object Tableviewpagecontrol {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 66  | Type: discreet info</summary>
	public System.Object Discreetinfo_discreetinfo {get { return GetParameter(66); }set { SetParameter(66, value); }}
	/// <summary>PID: 99  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixcolumntype_99 {get { return GetParameter(99); }set { SetParameter(99, value); }}
	/// <summary>PID: 99  | Type: read</summary>
	public System.Object Matrixcolumntype {get { return GetParameter(99); }set { SetParameter(99, value); }}
	/// <summary>PID: 101  | Type: write</summary>
	public System.Object Matrix_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: write</summary>
	public System.Object Matrix {get { return Write.Matrix; }set { Write.Matrix = value; }}
	/// <summary>PID: 105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixserialized_105 {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 105  | Type: read</summary>
	public System.Object Matrixserialized {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 124  | Type: read | DISCREETS: Matrix = 1, Tables = 2, Matrix and Tables = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixsettings_displaytype_124 {get { return GetParameter(124); }set { SetParameter(124, value); }}
	/// <summary>PID: 124  | Type: read | DISCREETS: Matrix = 1, Tables = 2, Matrix and Tables = 3</summary>
	public System.Object Matrixsettings_displaytype {get { return GetParameter(124); }set { SetParameter(124, value); }}
	/// <summary>PID: 125  | Type: write | DISCREETS: Matrix = 1, Tables = 2, Matrix and Tables = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Matrixsettings_displaytype_125 {get { return GetParameter(125); }set { SetParameter(125, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsnumber_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Routercontrolinputsnumber {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputslabel_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Routercontrolinputslabel {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsisenabled_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Routercontrolinputsisenabled {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Unlocked = 0, Locked = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsislocked_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Unlocked = 0, Locked = 1</summary>
	public System.Object Routercontrolinputsislocked {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsnotes_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	public System.Object Routercontrolinputsnotes {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1052  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputslabel_1052 {get { return GetParameter(1052); }set { SetParameter(1052, value); }}
	/// <summary>PID: 1053  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsisenabled_1053 {get { return GetParameter(1053); }set { SetParameter(1053, value); }}
	/// <summary>PID: 1054  | Type: write | DISCREETS: Unlocked = 0, Locked = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsislocked_1054 {get { return GetParameter(1054); }set { SetParameter(1054, value); }}
	/// <summary>PID: 1055  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsnotes_1055 {get { return GetParameter(1055); }set { SetParameter(1055, value); }}
	/// <summary>PID: 1101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsnumber_1101 {get { return GetParameter(1101); }set { SetParameter(1101, value); }}
	/// <summary>PID: 1101  | Type: read</summary>
	public System.Object Routercontroloutputsnumber {get { return GetParameter(1101); }set { SetParameter(1101, value); }}
	/// <summary>PID: 1102  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputslabel_1102 {get { return GetParameter(1102); }set { SetParameter(1102, value); }}
	/// <summary>PID: 1102  | Type: read</summary>
	public System.Object Routercontroloutputslabel {get { return GetParameter(1102); }set { SetParameter(1102, value); }}
	/// <summary>PID: 1103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsisenabled_1103 {get { return GetParameter(1103); }set { SetParameter(1103, value); }}
	/// <summary>PID: 1103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Routercontroloutputsisenabled {get { return GetParameter(1103); }set { SetParameter(1103, value); }}
	/// <summary>PID: 1104  | Type: read | DISCREETS: Unlocked = 0, Locked = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsislocked_1104 {get { return GetParameter(1104); }set { SetParameter(1104, value); }}
	/// <summary>PID: 1104  | Type: read | DISCREETS: Unlocked = 0, Locked = 1</summary>
	public System.Object Routercontroloutputsislocked {get { return GetParameter(1104); }set { SetParameter(1104, value); }}
	/// <summary>PID: 1105  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsnotes_1105 {get { return GetParameter(1105); }set { SetParameter(1105, value); }}
	/// <summary>PID: 1105  | Type: read</summary>
	public System.Object Routercontroloutputsnotes {get { return GetParameter(1105); }set { SetParameter(1105, value); }}
	/// <summary>PID: 1106  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsconnectedinput_1106 {get { return GetParameter(1106); }set { SetParameter(1106, value); }}
	/// <summary>PID: 1106  | Type: read</summary>
	public System.Object Routercontroloutputsconnectedinput {get { return GetParameter(1106); }set { SetParameter(1106, value); }}
	/// <summary>PID: 1152  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputslabel_1152 {get { return GetParameter(1152); }set { SetParameter(1152, value); }}
	/// <summary>PID: 1153  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsisenabled_1153 {get { return GetParameter(1153); }set { SetParameter(1153, value); }}
	/// <summary>PID: 1154  | Type: write | DISCREETS: Unlocked = 0, Locked = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsislocked_1154 {get { return GetParameter(1154); }set { SetParameter(1154, value); }}
	/// <summary>PID: 1155  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsnotes_1155 {get { return GetParameter(1155); }set { SetParameter(1155, value); }}
	/// <summary>PID: 1156  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsconnectedinput_1156 {get { return GetParameter(1156); }set { SetParameter(1156, value); }}
	/// <summary>PID: 1160  | Type: write</summary>
	public System.Object Routercontroloutputsvirtualsets_1160 {get { return GetParameter(1160); }set { SetParameter(1160, value); }}
	/// <summary>PID: 1160  | Type: write</summary>
	public System.Object Routercontroloutputsvirtualsets {get { return Write.Routercontroloutputsvirtualsets; }set { Write.Routercontroloutputsvirtualsets = value; }}
	/// <summary>PID: 1161  | Type: write</summary>
	public System.Object Routercontroloutputsserializedsets_1161 {get { return GetParameter(1161); }set { SetParameter(1161, value); }}
	/// <summary>PID: 1161  | Type: write</summary>
	public System.Object Routercontroloutputsserializedsets {get { return Write.Routercontroloutputsserializedsets; }set { Write.Routercontroloutputsserializedsets = value; }}
	/// <summary>PID: 1201  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsinstance_1201 {get { return GetParameter(1201); }set { SetParameter(1201, value); }}
	/// <summary>PID: 1201  | Type: read</summary>
	public System.Object Routersysleveloutputsinstance {get { return GetParameter(1201); }set { SetParameter(1201, value); }}
	/// <summary>PID: 1202  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsname_1202 {get { return GetParameter(1202); }set { SetParameter(1202, value); }}
	/// <summary>PID: 1202  | Type: read</summary>
	public System.Object Routersysleveloutputsname {get { return GetParameter(1202); }set { SetParameter(1202, value); }}
	/// <summary>PID: 1203  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputslocked_1203 {get { return GetParameter(1203); }set { SetParameter(1203, value); }}
	/// <summary>PID: 1203  | Type: read</summary>
	public System.Object Routersysleveloutputslocked {get { return GetParameter(1203); }set { SetParameter(1203, value); }}
	/// <summary>PID: 1204  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsinputstatus_1204 {get { return GetParameter(1204); }set { SetParameter(1204, value); }}
	/// <summary>PID: 1204  | Type: read</summary>
	public System.Object Routersysleveloutputsinputstatus {get { return GetParameter(1204); }set { SetParameter(1204, value); }}
	/// <summary>PID: 1301  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputsinstance_1301 {get { return GetParameter(1301); }set { SetParameter(1301, value); }}
	/// <summary>PID: 1301  | Type: read</summary>
	public System.Object Routersyslevelinputsinstance {get { return GetParameter(1301); }set { SetParameter(1301, value); }}
	/// <summary>PID: 1302  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputsname_1302 {get { return GetParameter(1302); }set { SetParameter(1302, value); }}
	/// <summary>PID: 1302  | Type: read</summary>
	public System.Object Routersyslevelinputsname {get { return GetParameter(1302); }set { SetParameter(1302, value); }}
	/// <summary>PID: 1303  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputslocked_1303 {get { return GetParameter(1303); }set { SetParameter(1303, value); }}
	/// <summary>PID: 1303  | Type: read</summary>
	public System.Object Routersyslevelinputslocked {get { return GetParameter(1303); }set { SetParameter(1303, value); }}
	/// <summary>PID: 1400  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelwritebuffer_1400 {get { return GetParameter(1400); }set { SetParameter(1400, value); }}
	/// <summary>PID: 1400  | Type: read</summary>
	public System.Object Routersyslevelwritebuffer {get { return GetParameter(1400); }set { SetParameter(1400, value); }}
	/// <summary>PID: 1401  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelwriteoid_1401 {get { return GetParameter(1401); }set { SetParameter(1401, value); }}
	/// <summary>PID: 1401  | Type: read</summary>
	public System.Object Routersyslevelwriteoid {get { return GetParameter(1401); }set { SetParameter(1401, value); }}
	/// <summary>PID: 1402  | Type: write</summary>
	public System.Object Routersyslevelwritevalue_1402 {get { return GetParameter(1402); }set { SetParameter(1402, value); }}
	/// <summary>PID: 1402  | Type: write</summary>
	public System.Object Routersyslevelwritevalue {get { return Write.Routersyslevelwritevalue; }set { Write.Routersyslevelwritevalue = value; }}
	/// <summary>PID: 1403  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelreadvalue_1403 {get { return GetParameter(1403); }set { SetParameter(1403, value); }}
	/// <summary>PID: 1403  | Type: read</summary>
	public System.Object Routersyslevelreadvalue {get { return GetParameter(1403); }set { SetParameter(1403, value); }}
	/// <summary>PID: 1404  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveltakenextwritebufferitem_1404 {get { return GetParameter(1404); }set { SetParameter(1404, value); }}
	/// <summary>PID: 1404  | Type: read</summary>
	public System.Object Routersysleveltakenextwritebufferitem {get { return GetParameter(1404); }set { SetParameter(1404, value); }}
	/// <summary>PID: 1405  | Type: write</summary>
	public System.Object Routersyslevelwritevalueinteger_1405 {get { return GetParameter(1405); }set { SetParameter(1405, value); }}
	/// <summary>PID: 1405  | Type: write</summary>
	public System.Object Routersyslevelwritevalueinteger {get { return Write.Routersyslevelwritevalueinteger; }set { Write.Routersyslevelwritevalueinteger = value; }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		matrix = new MatrixQActionTable(this, 100, "matrix");
		routercontrolinputs = new RoutercontrolinputsQActionTable(this, 1000, "routercontrolinputs");
		routercontroloutputs = new RoutercontroloutputsQActionTable(this, 1100, "routercontroloutputs");
		routersysleveloutputs = new RoutersysleveloutputsQActionTable(this, 1200, "routersysleveloutputs");
		routersyslevelinputs = new RoutersyslevelinputsQActionTable(this, 1300, "routersyslevelinputs");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class MatrixQActionTable : QActionTable, IEnumerable<MatrixQActionRow>
{
	public MatrixQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<MatrixQActionRow> GetEnumerator() { return new QActionTableEnumerator<MatrixQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class RoutercontrolinputsQActionTable : QActionTable, IEnumerable<RoutercontrolinputsQActionRow>
{
	public RoutercontrolinputsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<RoutercontrolinputsQActionRow> GetEnumerator() { return new QActionTableEnumerator<RoutercontrolinputsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class RoutercontroloutputsQActionTable : QActionTable, IEnumerable<RoutercontroloutputsQActionRow>
{
	public RoutercontroloutputsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<RoutercontroloutputsQActionRow> GetEnumerator() { return new QActionTableEnumerator<RoutercontroloutputsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class RoutersysleveloutputsQActionTable : QActionTable, IEnumerable<RoutersysleveloutputsQActionRow>
{
	public RoutersysleveloutputsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<RoutersysleveloutputsQActionRow> GetEnumerator() { return new QActionTableEnumerator<RoutersysleveloutputsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class RoutersyslevelinputsQActionTable : QActionTable, IEnumerable<RoutersyslevelinputsQActionRow>
{
	public RoutersyslevelinputsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<RoutersyslevelinputsQActionRow> GetEnumerator() { return new QActionTableEnumerator<RoutersyslevelinputsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class MatrixQActionRow : QActionTableRow
{
	public MatrixQActionRow() : base(0, 0) { }
	public MatrixQActionRow(System.Object[] oRow) : base(0, 0, oRow) { }
	public static implicit operator MatrixQActionRow(System.Object[] source) { return new MatrixQActionRow(source); }
	public static implicit operator System.Object[](MatrixQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class RoutercontrolinputsQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsnumber_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Routercontrolinputsnumber { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputslabel_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Routercontrolinputslabel { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsisenabled_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Routercontrolinputsisenabled { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsislocked_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Routercontrolinputsislocked { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontrolinputsnotes_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Routercontrolinputsnotes { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	public RoutercontrolinputsQActionRow() : base(0, 5) { }
	public RoutercontrolinputsQActionRow(System.Object[] oRow) : base(0, 5, oRow) { }
	public static implicit operator RoutercontrolinputsQActionRow(System.Object[] source) { return new RoutercontrolinputsQActionRow(source); }
	public static implicit operator System.Object[](RoutercontrolinputsQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class RoutercontroloutputsQActionRow : QActionTableRow
{
	/// <summary>PID: 1101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsnumber_1101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1101 | Type: read</summary>
	public System.Object Routercontroloutputsnumber { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputslabel_1102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1102 | Type: read</summary>
	public System.Object Routercontroloutputslabel { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsisenabled_1103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1103 | Type: read</summary>
	public System.Object Routercontroloutputsisenabled { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1104 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsislocked_1104 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1104 | Type: read</summary>
	public System.Object Routercontroloutputsislocked { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsnotes_1105 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1105 | Type: read</summary>
	public System.Object Routercontroloutputsnotes { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1106 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routercontroloutputsconnectedinput_1106 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1106 | Type: read</summary>
	public System.Object Routercontroloutputsconnectedinput { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	public RoutercontroloutputsQActionRow() : base(0, 6) { }
	public RoutercontroloutputsQActionRow(System.Object[] oRow) : base(0, 6, oRow) { }
	public static implicit operator RoutercontroloutputsQActionRow(System.Object[] source) { return new RoutercontroloutputsQActionRow(source); }
	public static implicit operator System.Object[](RoutercontroloutputsQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class RoutersysleveloutputsQActionRow : QActionTableRow
{
	/// <summary>PID: 1201 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsinstance_1201 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1201 | Type: read</summary>
	public System.Object Routersysleveloutputsinstance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1202 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsname_1202 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1202 | Type: read</summary>
	public System.Object Routersysleveloutputsname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1203 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputslocked_1203 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1203 | Type: read</summary>
	public System.Object Routersysleveloutputslocked { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1204 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersysleveloutputsinputstatus_1204 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1204 | Type: read</summary>
	public System.Object Routersysleveloutputsinputstatus { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	public RoutersysleveloutputsQActionRow() : base(0, 4) { }
	public RoutersysleveloutputsQActionRow(System.Object[] oRow) : base(0, 4, oRow) { }
	public static implicit operator RoutersysleveloutputsQActionRow(System.Object[] source) { return new RoutersysleveloutputsQActionRow(source); }
	public static implicit operator System.Object[](RoutersysleveloutputsQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class RoutersyslevelinputsQActionRow : QActionTableRow
{
	/// <summary>PID: 1301 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputsinstance_1301 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1301 | Type: read</summary>
	public System.Object Routersyslevelinputsinstance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1302 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputsname_1302 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1302 | Type: read</summary>
	public System.Object Routersyslevelinputsname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1303 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Routersyslevelinputslocked_1303 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1303 | Type: read</summary>
	public System.Object Routersyslevelinputslocked { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	public RoutersyslevelinputsQActionRow() : base(0, 3) { }
	public RoutersyslevelinputsQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
	public static implicit operator RoutersyslevelinputsQActionRow(System.Object[] source) { return new RoutersyslevelinputsQActionRow(source); }
	public static implicit operator System.Object[](RoutersyslevelinputsQActionRow source) { return source.ToObjectArray(); }
}
}
